export const API_ENDPOINTS = {
    AUTH: {
        LOGIN: '/api/auth/login',
        REGISTER: '/api/auth/register',
        LOGOUT: '/api/auth/logout',
        REFRESH: '/api/auth/refresh-token',
        FORGOT_PASSWORD: '/api/auth/forgot-password',
        RESET_PASSWORD: '/api/auth/reset-password',
        VERIFY_EMAIL: '/api/auth/verify',
        GOOGLE: '/api/auth/google',
        GITHUB: '/api/auth/github',
        ME: '/api/auth/me',
        VERIFY_2FA: '/api/auth/verify-2fa',
    },
    BLOGS: { BASE: '/api/blogs', BY_ID: (id: string) => `/api/blogs/${id}` },
    CHALLENGES: { BASE: '/api/challenges', BY_SLUG: (slug: string) => `/api/challenges/${slug}`, SUBMIT: (id: string) => `/api/challenges/${id}/submit`, HINT: (id: string) => `/api/challenges/${id}/hint` },
    EVENTS: { BASE: '/api/events', BY_SLUG: (slug: string) => `/api/events/${slug}`, REGISTER: (id: string) => `/api/events/${id}/register`, UPCOMING: '/api/events/upcoming' },
    FORUMS: { DISCUSSIONS: '/api/forums/discussions', BY_ID: (id: string) => `/api/forums/discussions/${id}`, REPLIES: (id: string) => `/api/forums/discussions/${id}/replies` },
    FEED: { BASE: '/api/feed', BY_ID: (id: string) => `/api/feed/${id}`, LIKE: (id: string) => `/api/feed/${id}/like`, COMMENT: (id: string) => `/api/feed/${id}/comments` },
    JOBS: { BASE: '/api/jobs', BY_SLUG: (slug: string) => `/api/jobs/${slug}`, APPLY: (id: string) => `/api/jobs/${id}/apply`, EMPLOYER: '/api/jobs/employer' },
    USERS: { BASE: '/api/users', BY_USERNAME: (username: string) => `/api/users/${username}`, SEARCH: '/api/users/search' },
    LEADERBOARD: { BASE: '/api/leaderboard' },
    SEARCH: { BASE: '/api/search' },
    NOTIFICATIONS: { BASE: '/api/notifications', UNREAD: '/api/notifications/unread-count', READ: (id: string) => `/api/notifications/${id}/read`, READ_ALL: '/api/notifications/read-all' },
    BOOKMARKS: { BASE: '/api/bookmarks', COLLECTIONS: '/api/bookmarks/collections' },
    MENTORSHIP: { BASE: '/api/mentorship', MENTORS: '/api/mentor', REQUESTS: '/api/mentorship-requests' },
    INTERNSHIPS: { BASE: '/api/internships', BY_ID: (id: string) => `/api/internships/${id}`, APPLY: (id: string) => `/api/internships/${id}/apply` },
    LEARNING_PATHS: { BASE: '/api/learning-paths', BY_SLUG: (slug: string) => `/api/learning-paths/${slug}` },
    UPLOAD: { AVATAR: '/api/upload/avatar', MEDIA: '/api/upload/media' },
    HEALTH: { BASE: '/api/health' },
    DAILY_CHALLENGE: { TODAY: '/api/daily-challenges/today', SUBMIT: '/api/daily-challenges/submit' },
    STREAK: { BASE: '/api/streak', CHECKIN: '/api/streak/checkin' },
} as const;
